read-only-non-proxy-mapping
ba-st/Sagan pull request #35
Opened 2020-03-04 13:58 UTC by HurrellT

Adding read only non proxy mapping

2020-03-11 14:23 UTC, fortizpenaloza requested changes
The new method is not categorized and you does not provide a test

2020-08-28 12:17 UTC, gcotelli requested changes
@fortizpenaloza already requested the changes :)

2020-08-28 12:18 UTC, gcotelli commented
And there was a lot of changes in the meantime, so better merge release-candidate first into this branch.

2020-09-10 16:06 UTC, gcotelli approved these changes

2020-09-10 16:11 UTC, merged